config/routes.rb
Rails.application.routes.draw do
  root "tasks#home"

  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :tasks
  resources :pets

  get ":username" => "users#show", as: :user
  get ":username/tasks" => "users#tasks", as: :user_tasks
  get ":username/completed" => "users#completed", as: :completed
  get ":username/failed" => "users#failed", as: :failed
  get ":username/pets" => "users#pets", as: :user_pets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id           :bigint           not null, primary key
#  happiness    :integer          default(50)
#  image        :string
#  name         :string           not null
#  status       :string           default(NULL)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  pet_owner_id :bigint           not null
#
# Indexes
#
#  index_pets_on_pet_owner_id  (pet_owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (pet_owner_id => users.id)
#
class Pet < ApplicationRecord
  belongs_to :pet_owner, class_name: "User"
  enum status: {pending: "neutral", happy: "happy", sad: "sad"}
  attribute :happiness, :integer, default: 50
  

  def status
    if happiness >= 70
       "happy"
    elsif happiness >= 40
       "neutral"
    else
       "sad"
    end
  end

  validates :name, presence: true

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]
  helper_method :get_random_image_path

  # GET /pets or /pets.json
  def index
    @pets = current_user.own_pets
    @pets.each do |pet|
      pet.status
    end
  end

  # GET /pets/1 or /pets/1.json
  def show
    @pets = current_user.own_pets
    @pets.each do |pet|
      pet.status
    end
    advice_url = HTTP.get("https://api.adviceslip.com/advice")
    advice_data = JSON.parse(advice_url).fetch("slip")
    @advice = advice_data.fetch("advice")

  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  def get_random_image_path
    images = Dir.glob(Rails.root.join("app", "assets", "images", "pets", "*.{jpg,jpeg,png,gif}"))
    images.sample.split("/").last
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.pet_owner = current_user
    @pet.image = params[:pet][:image]
    if @pet.happiness >= 40
      @pet.status = "neutral"
    end

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "You got a task pet! Please start making them happy by completing tasks." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to root_path, alert: "Pet was released." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pet_params
    params.require(:pet).permit(:pet_owner_id, :name, :status, :image)
  end
end

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :image, value: get_random_image_path %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


   <div>
    <%= form.submit "Welcome Task Pet!", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <div class = "container mb-3">
    <div class="col">
      <% if pet.status == "neutral" %>
        <div class="card text-bg-light">
        <% elsif pet.status == "happy" %>
          <div class="card text-bg-success">
          <% elsif pet.status == "sad" %>
            <div class="card text-bg-dark">
            <% end %>

            <div class="card-header">
              Status: <%= pet.status %>
            </div>

            <div class="card-body">
              <div class="d-flex justify-content-center mb-3">
                <% if pet.image == "catgif1.gif"%>
                  <%= image_tag "pets/catgif1.gif", alt:"cat1", class: "cat2", style: "max-width: 30%;" %>
                <% elsif pet.image == "catgif2.gif"%>
                  <%= image_tag "pets/catgif2.gif", alt:"cat2", class: "cat2", style: "max-width: 30%;" %>
                <% elsif pet.image == "catgif3.gif"%>
                  <%= image_tag "pets/catgif3.gif", alt:"cat3", class: "cat3", style: "max-width: 30%;" %>
                <% elsif pet.image == "catgif4.gif"%>
                  <%= image_tag "pets/catgif4.gif", alt:"cat4", class: "cat4", style: "max-width: 30%;" %>
                <% elsif pet.image == "catgif5.gif"%>
                  <%= image_tag "pets/catgif5.gif", alt:"cat5", class: "cat5", style: "max-width: 30%;" %>
                <% end %>
              </div>

              <h5 class="card-title text-center">Name: <%= pet.name.capitalize %></h5>
              <p class="card-text text-center">Happiness: <%= pet.happiness %></p>
            </div>
              <div class="d-flex justify-content-center mb-3">
              <%= button_to "Show this pet", pet, method: :get, class: "btn btn-primary" %>
              </div>
          </div>
        </div>
      </div>
    </div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= form_with(model: @pet) do |form| %>
  <% if @pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% @pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


   <div>
    <%= form.submit "Submit changes", class: "btn btn-primary btn-block"%>
  </div>

<% end %>

<br>

<div>
  <%= link_to "Back to pets", user_pets_path(username: current_user.username)%>
</div>

app/views/pets/index.html.erb
<h1>Pets</h1>

<div id="pets">
  <% @pets.each do |pet| %>
    <%= render pet %>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="d-flex justify-content-center">
  <h1>New pet</h1>
</div>

<div class="d-flex justify-content-center">
  <%= render "form", pet: @pet %>
</div>

  <div class="container text-center mb-3">
    <%= image_tag "pawprint.gif", alt: "animal1", class: "img-fluid animal1", style: "max-width: 50%;" %>
  </div>

app/views/pets/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="d-flex justify-content-center mb-3">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#PetAdvice">
    Get advice from <%= @pet.name.capitalize %>
  </button>

  <div class="modal fade" id="PetAdvice" tabindex="-1" aria-labelledby="PetAdviceLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="PetAdviceLabel" style="color: black;"><%= @pet.name.capitalize %> wants to tell you...</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p style="color: black;"><%= @advice %></p>
        </div>
      </div>
    </div>
  </div>

</div>

<div class = "container">
  <%= render @pet %>
</div>


<div class="d-flex justify-content-center mb-3">
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", user_pets_path(username: current_user.username)%>
</div>

<div class="d-flex justify-content-center mb-3">
  <%= button_to "Release this pet?", @pet, method: :delete, class: "btn btn-danger" %>
</div>

app/views/pets/welcome_message.html.erb
<h1>Welcome to the Task Pet App!</h1>
<p>A task pet has found you! Let's create and name your new pet.</p>
  <%= button_to new_pet_path, method: :get, class: "btn btn-primary" do %>
    <i class="fa-solid fa-paw"></i>
    Name your task pet!
  <% end %>