config/routes.rb
Rails.application.routes.draw do
  root "tasks#home"

  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :tasks
  resources :pets

  get ":username" => "users#show", as: :user
  get ":username/tasks" => "users#tasks", as: :user_tasks
  get ":username/completed" => "users#completed", as: :completed
  get ":username/failed" => "users#failed", as: :failed
  get ":username/pets" => "users#pets", as: :user_pets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  avatar_image           :string           default("avatar_placeholder.png")
#  email                  :citext           default(""), not null
#  encrypted_password     :string           default(""), not null
#  private                :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :citext
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :own_tasks, class_name: "Task", foreign_key: "task_owner_id"
  has_many :own_pets, class_name: "Pet", foreign_key: "pet_owner_id"



 
  validates :username, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params.fetch(:username))
  end

  def tasks
    @user = User.find_by!(username: params.fetch(:username))
  end

  def completed
    @user = User.find_by!(username: params.fetch(:username))
  end

  def failed
    @user = User.find_by!(username: params.fetch(:username))
  end

  def pets
    @user = User.find_by!(username: params.fetch(:username))
  end
end

app/views/users/_profile.html.erb
<div class="container-fluid d-flex justify-content-center align-items-center flex-column">
  <div class="container mb-3">
    <div class="row">
      <div class="col-lg-3 mx-auto ">
        <h1><%= @user.username.capitalize %>'s Profile</h1>
        <div class="card" style="max-width: 15rem;">
          <% if @user.avatar_image.present? %>
            <div class="card-body d-flex justify-content-center">
              <%= image_tag @user.avatar_image, class: "card-img-top" %>
            </div>
          <% end %>
          <div class="card-body p-3">
            <p class="card-text">Member since: <%= @user.created_at.strftime("%B %d, %Y") %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container mb-3">

    <div class="col-lg-6 mx-auto">
      <ul class="nav nav-tabs mt-4 justify-content-center">
        <li class="nav-item">
          <%= link_to "Pending", user_path(@user.username), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Completed", completed_path(@user.username), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Failed", failed_path(@user.username), class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/completed.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= render "profile" %>

<div class="d-flex justify-content-center mb-3">
  <h3><%= @user.username.capitalize %>'s Completed Tasks</h3>
</div>
<div class = "container mb-3">
  <% @user.own_tasks.each do |task| %>
    <% if task.status == "completed" %>
      <%= render "tasks/task", task: task %>
    <% end %>
  <% end %>
</div>

<br>

<div class="container mb-3">
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center mb-3">
        <h2><%= @user.username.capitalize %>'s Pets</h2>
      </div>
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <% @user.own_pets.each do |pet| %>
          <%= render "pets/pet", pet: pet %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/failed.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= render "profile" %>

<div class="d-flex justify-content-center mb-3">
  <h3><%= @user.username.capitalize %>'s Failed Tasks</h3>
</div>

<div class = "container">
  <% @user.own_tasks.each do |task| %>
    <% if task.status == "failed" %>
      <%= render "tasks/task", task: task %>
    <% end %>
  <% end %>
</div>

<br>

<div class="container mb-3">
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center mb-3">
        <h2><%= @user.username.capitalize %>'s Pets</h2>
      </div>
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <% @user.own_pets.each do |pet| %>
          <%= render "pets/pet", pet: pet %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/pets.html.erb
<div>
  <h2><%= @user.username.capitalize %>'s pets </h2>
  <div class = "container mb-3" >
    <div class="row row-cols-1 row-cols-md-2 g-4">
      <% @user.own_pets.each do |pet| %>
        <%= render "pets/pet", pet: pet %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= render "profile" %>

<div class="d-flex justify-content-center mb-3">
  <h3><%= @user.username.capitalize %>'s Pending Tasks</h3>
</div>

<div class = "container mb-3">
  <% @user.own_tasks.each do |task| %>
    <% if task.status == "pending" %>
      <%= render "tasks/task", task: task %>
    <% end %>
  <% end %>
</div>

<br>

<div class="container mb-3">
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content-center mb-3">
        <h2><%= @user.username.capitalize %>'s Pets</h2>
      </div>
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <% @user.own_pets.each do |pet| %>
          <%= render "pets/pet", pet: pet %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/tasks.html.erb
<div class = "container mb-3">
  <h2><%= @user.username.capitalize %>'s task list </h2>
</div>

<div class = "container">
  <% @user.own_tasks.each do |task| %>
    <%= link_to "Show this task", task_path(task), method: :get %>
    <%= render "tasks/task", task: task %>
  <% end %>
</div>