config/routes.rb
Rails.application.routes.draw do
  root "tasks#home"

  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :tasks
  resources :pets

  get ":username" => "users#show", as: :user
  get ":username/tasks" => "users#tasks", as: :user_tasks
  get ":username/completed" => "users#completed", as: :completed
  get ":username/failed" => "users#failed", as: :failed
  get ":username/pets" => "users#pets", as: :user_pets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
end

app/views/shared/_cdn_assets.html.erb
<!-- app/views/shared/_cdn_assets.html.erb -->

<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <%= link_to "P.A.T.S", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to new_task_path, class: "nav-link" do %>
              <i class="fa-solid fa-clipboard-list"></i> Add task
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_pet_path, class: "nav-link" do %>
              <i class="fa-solid fa-paw"></i> Add pet
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.username), class: "nav-link" do %>
              <i class="fas fa-home fa-fw"></i> Your profile
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Tasks list", user_tasks_path(username: current_user.username), class: "dropdown-item" %>
              <%= link_to "Check pets", user_pets_path(username: current_user.username), class: "dropdown-item"%>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fa-solid fa-cat"></i> Sign in
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              <i class="fa-solid fa-dog"></i> Sign up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>